DogHome/DogHome/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainPage.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DogHome/MainPage/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

urlpatterns = [
    path('', Main.as_view(), name='main'),
    path('dog_cards/', DogCard.as_view(), name='dogCards'),
    path('shelter/', ShelterCard.as_view(), name='shelterDog'),
    path('dog_cards/<int:pk>', ViewDog.as_view(), name='viewdog'),
    path('dog_cards/filter/<int:shelter_id>', DogCard.as_view(), name='shelterbydogs'),
    path('shelter/<int:pk>', ViewShelter.as_view(), name='viewshelter'),
    path('help_for_shelters/', HelpForShelter.as_view(), name='helpforshelters')
]

DogHome/MainPage/models.py
from django.db import models
from django.urls import reverse
from PIL import Image
from django.core.exceptions import ValidationError


def validate_image_size_Dog(value):
    image = Image.open(value)
    width, height = image.size
    mix_width = 640
    mix_height = 640

    if width < mix_width or height < mix_height:
        raise ValidationError(f"Минимальный размеры изображения: {mix_width}x{mix_height} пикселей.")


class Dog(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    GENDER_CHOICES = (
        (True, 'Мужской'),
        (False, 'Женский'),
    )
    gender = models.BooleanField(choices=GENDER_CHOICES, verbose_name='Пол')
    weight = models.IntegerField(verbose_name='Вес')
    height = models.IntegerField(verbose_name='Рост')
    description = models.TextField(blank=True, verbose_name='Описание')
    YES_NO_CHOICES = (
        (True, 'Да'),
        (False, 'Нет'),
    )
    owner = models.BooleanField(choices=YES_NO_CHOICES, verbose_name='Был ли хозяин')
    age = models.IntegerField(verbose_name='Возраст')
    color = models.CharField(max_length=100, blank=True, verbose_name='Окрас')
    breed = models.ForeignKey('Breed', on_delete=models.SET_NULL, verbose_name='Название породы', blank=True, null=True,
                              default=None)
    health = models.ForeignKey('Health', on_delete=models.SET_NULL, verbose_name='Здоровье', blank=True, null=True,
                               default=None)
    shelter = models.ForeignKey('Shelter', on_delete=models.PROTECT, verbose_name='Приют', blank=True)
    photo = models.ImageField(upload_to='photos/dog/%Y/%m/%d/', verbose_name='Фото', blank=True,
                              validators=[validate_image_size_Dog])

    def get_absolute_url(self):
        return reverse('viewdog', kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Собака'
        verbose_name_plural = 'Собаки'


def validate_image_size_Shelter(value):
    image = Image.open(value)
    width, height = image.size
    mix_width = 550
    mix_height = 360

    if width < mix_width or height < mix_height:
        raise ValidationError(f"Минимальный размеры изображения: {mix_width}x{mix_height} пикселей.")


class Shelter(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    year_of_creation = models.DateField(verbose_name='Год создания', blank=True)
    number_of_animals = models.IntegerField(verbose_name='Количество животных')
    description = models.TextField(blank=True, verbose_name='Описание')
    address = models.TextField(verbose_name='Адрес')
    contacts = models.CharField(max_length=11, verbose_name='Контакты')
    contact_person = models.CharField(max_length=100, verbose_name='Контактное лицо')
    photo = models.ImageField(upload_to='photos/shelter/%Y/%m/%d/', verbose_name='Фото', blank=True,
                              validators=[validate_image_size_Shelter])

    def get_absolute_url(self):
        return reverse('viewshelter', kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Приют'
        verbose_name_plural = 'Приюты'


class ShelterPhoto(models.Model):
    shelter = models.ForeignKey(Shelter, related_name='photos', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='photos/shelter/%Y/%m/%d/', verbose_name='Фото', blank=True)
    description = models.TextField(verbose_name='Описание', blank=True)

    class Meta:
        verbose_name = 'Фото приютов'
        verbose_name_plural = 'Фото приютов'

    def __str__(self):
        return self.description


def validate_image_size_Employee(value):
    image = Image.open(value)
    width, height = image.size
    mix_width = 450
    mix_height = 600

    if width < mix_width or height < mix_height:
        raise ValidationError(f"Минимальный размеры изображения: {mix_width}x{mix_height} пикселей.")


class Employee(models.Model):
    name = models.CharField(max_length=100, verbose_name='ФИО')
    job_title = models.CharField(max_length=100, verbose_name='Должность')
    description = models.TextField(blank=True, verbose_name='Описание')
    photo = models.ImageField(upload_to='photos/employee/%Y/%m/%d/', verbose_name='Фото', blank=True,
                              validators=[validate_image_size_Employee])
    shelter = models.ForeignKey(Shelter, related_name='job', on_delete=models.PROTECT, verbose_name='Место работы',
                                blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'


class Health(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    symptoms = models.TextField(verbose_name='Симптомы', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Здоровье'
        verbose_name_plural = 'Здоровье'


class Breed(models.Model):
    name = models.CharField(max_length=100, verbose_name='Порода')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Порода'
        verbose_name_plural = 'Породы'

DogHome/MainPage/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
from django.db.models import Q
from .models import Shelter, Dog, ShelterPhoto, Employee


class Main(ListView):
    model = Shelter
    template_name = 'MainPage/home_main_list.html'
    context_object_name = 'shelter'


class DogCard(ListView):
    model = Dog
    template_name = 'MainPage/dog_card_list.html'
    context_object_name = 'dogs'

    # Метод для вывода кнопок приютов
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['unique_shelters'] = Shelter.objects.all()
        shelter_id = self.kwargs.get('shelter_id')
        if shelter_id:
            selected_shelter = get_object_or_404(Shelter, id=shelter_id)
            context['selected_shelter'] = selected_shelter
        return context

    def get_queryset(self):
        queryset = super().get_queryset()

        shelter_id = self.kwargs.get('shelter_id')
        if shelter_id:
            queryset = queryset.filter(shelter_id=shelter_id)

        query = self.request.GET.get('q')
        if query:
            queryset = Dog.objects.filter(Q(name__icontains=query))
        return queryset


class ShelterCard(ListView):
    model = Shelter
    template_name = 'MainPage/shelter_card_list.html'
    context_object_name = 'shelters'

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('q')
        if query:
            queryset = Shelter.objects.filter(Q(name__icontains=query))
        return queryset


class ViewDog(DetailView):
    model = Dog
    context_object_name = 'dog_item'
    template_name = 'MainPage/view_dog_list.html'


class ViewShelter(DetailView):
    model = Shelter
    template_name = 'MainPage/view_shelter_list.html'
    context_object_name = 'shelters'


class HelpForShelter(ListView):
    model = Employee
    template_name = 'MainPage/help_for_shelters_list.html'
    context_object_name = 'employee'

DogHome/MainPage/templates/MainPage/dog_card_list.html
{% extends 'base.html' %}

{%block title%}Наши собачки{%endblock%}

{% block content %}

<div style="text-align:center">
    <h2 class="title">
        Собаки
    </h2>
</div>

<div class="container mt-5">
    <div class="row">
        <div class="container">
            <div class="row">
                <div class="col">
                    <a href="{% url 'dogCards' %}" class="btn button">Все</a>

                    {% for shelter in unique_shelters %}
                        <a href="{% url 'shelterbydogs' shelter_id=shelter.id %}" class="btn button">{{ shelter.name }}</a>
                    {% endfor %}
                </div>
                <div class="col-md-4">
                    <form action="{% url 'dogCards' %}" method="get" class="d-flex">
                        <input name="q" type="text" class="form-control me-2" placeholder="Имя собаки">
                    </form>
                </div>
            </div>
        </div>


        <h2 class="name">
            {% if selected_shelter %}
            {{ selected_shelter.name }}
            {% endif %}
        </h2>


        {% for item in dogs %}
        <div class="col-4 mt-4">
            <div class="card" id="borderCard" style="width: *25rem; height: *500px;">
                <div class="media">
                    {% if item.photo %}
                    <img src="{{ item.photo.url }}" width="220" height="350" class="card-img-top">
                    {% else %}
                    <img src="https://images.freeimages.com/images/large-previews/349/free-background-blur-1636598.jpg" width="220" height="350" class="card-img-top">
                    {% endif %}
                </div>
                <div class="card-body">
                    <h5 class="card-title name">{{ item.name }}</h5>
                    <p class="card-text">{{ item.description|truncatewords:5 }}</p>
                    <a href="{{ item.get_absolute_url }}" class="btn button">Читать...</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

DogHome/MainPage/templates/MainPage/help_for_shelters_list.html
{% extends 'base.html' %}

{%block title%}Помощь приютам{%endblock%}

{% block content %}


<div id="containerInfHelp" class="container border mt-2">
    <div style="text-align: center; border-radius: 1em">
        <img width="700" class="img-fluid" style="border-radius: 1em; padding: 0.5em; margin-top: 1em"
                 src="https://img.baba-blog.com/2024/02/what-are-top-dog-products-to-stock-in-2022_00.jpg?x-oss-process=style%2Ffull">
    </div>
    <h2 class="name" style="text-align: center; padding: 0.25em">Как помочь животным?</h2>
    <ul style=" text-align: justify;">
        <li style="font-size: 1.2em"><strong style="font-size: 1.5em">Волонтёрство:</strong> Проведите время в приюте, помогая с уходом за животными, выгулом собак и уборкой клеток.</li>
        <li style="font-size: 1.2em"><strong style="font-size: 1.5em">Пожертвования:</strong> Пожертвуйте финансовые средства или материальные ресурсы для поддержки приюта.</li>
        <li style="font-size: 1.2em"><strong style="font-size: 1.5em">Усыновление:</strong> Рассмотрите возможность усыновления животного из приюта.</li>
        <li style="font-size: 1.2em"><strong style="font-size: 1.5em">Распространение информации:</strong> Помогите распространить информацию о приюте и животных, нуждающихся в доме.</li>
        <li style="font-size: 1.2em"><strong style="font-size: 1.5em">Подарки в приют:</strong> Подарите приюту необходимые предметы для ухода за животными.</li>
        <li style="font-size: 1.2em"><strong style="font-size: 1.5em">Обучение и образование:</strong> Участвуйте в образовательных мероприятиях приюта.</li>
        <li style="font-size: 1.2em"><strong style="font-size: 1.5em">Профессиональные услуги:</strong> Предложите свою помощь приюту, если у вас есть профессиональные навыки, которые могут быть полезны.</li>
        <li style="font-size: 1.2em"><strong style="font-size: 1.5em">Поддержка приютов:</strong> Помогайте приютам с финансовым планированием, фондовыми мероприятиями и развитием сообщества.</li>
    </ul>
</div>
<div style="text-align:center">
    <h2 class="title">
        С кем можно связаться?
    </h2>
</div>
<div class="row">
    {% for item in employee %}
    <div class="col-md-4 mt-4">
        <div class="card" id="borderCard" style="width: *em; height: 70em;">
            <div class="media">
                {% if item.photo %}
                <img src="{{ item.photo.url }}" width="397" height="500" class="card-img-top">
                {% endif %}
            </div>
            <div class="card-body">
                <h5 class="card-title name">{{ item.name }}</h5>
                <p class="card-text">{{ item.description }}</p>
                {% if item.shelter %}
                    <a href="{% url 'viewshelter' item.shelter.id %}" style="width: 24em; position: absolute; bottom: 10px;" class="btn button">
                        {{ item.shelter.name }}
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{%endblock%}

DogHome/MainPage/templates/MainPage/home_main_list.html
{% extends 'base.html' %}


{% block content %}
<div id="carouselExampleAutoplaying" data-bs-ride="carousel" data-bs-interval="1500">
    <div id="carousel" class="carousel-inner">
        <div class="carousel-item active">
            <img width="1500" height="550" src="https://s0.rbk.ru/v6_top_pics/media/img/2/16/346928865645162.webp">
        </div>
        <div class="carousel-item">
            <img width="1500" height="550"
                 src="https://s9.stc.all.kpcdn.net/family/wp-content/uploads/2023/02/top-v-luchshie-porody-krupnykh-sobak-960x540-1-960x540.jpg">
        </div>
        <div class="carousel-item">
            <img width="1500" height="550" src="https://s0.rbk.ru/v6_top_pics/media/img/4/47/346915732996474.webp">
        </div>
    </div>
</div>


<div id="containerInf" class="container border mt-5">
    <div class="row">
        <div class="col-5">
            <img width="500" height="290" class="img-fluid" style="border-radius: 10em"
                 src="https://celes.club/uploads/posts/2021-12/1638823205_1-celes-club-p-mnogo-sobak-zhivotnie-krasivo-foto-1.jpg">
        </div>
        <div class="col-6">
            <h2 class="name">Информация о сайте</h2>

            <p align="justify"> Наш сайт предназначен для поддержки и содействия приютам для собак.
                Мы стремимся создать дружественное и поддерживающее онлайн-сообщество, которое поможет приютам собрать ресурсы,
                привлечь внимание общественности и обеспечить лучшие условия для своих подопечных.
            </p>
        </div>
    </div>
</div>


<div class="container mt-5">
    <div style="text-align: center;">
        <a id="buttonShelter" href="{% url 'shelterDog' %}" class="btn">Приюты</a>
    </div>
    <div class="row">
        {% for item in shelter%}
        <div class="col-4 mt-4">
            <div class="card" id="borderCard" style="width: *25rem; height: 500px;">
                <div class="media">
                    {% if item.photo %}
                    <img src="{{ item.photo.url }}" width="397" height="300" class="card-img-top">
                    {% endif %}
                </div>
                <div class="card-body">
                    <h5 class="card-title name">{{ item.name }}</h5>
                    <p class="card-text">{{ item.address }}</p>
                    <a href="{{ item.get_absolute_url }}" class="btn button">Читать</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

DogHome/MainPage/templates/MainPage/shelter_card_list.html
{% extends 'base.html' %}

{%block title%}Приюты{%endblock%}

{% block content %}
<div style="text-align:center">
    <h2 class="title">
        Приюты
    </h2>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-4">
            <form action="{% url 'shelterDog' %}" method="get" class="d-flex">
                <input name="q" type="text" class="form-control me-2" placeholder="Название приюта">
                <a href="{% url 'shelterDog' %}" class="btn button">Все</a>
            </form>
        </div>
    </div>

    <div class="row">
        {% for item in shelters %}
        <div class="col-4 mt-4">
            <div class="card" id="borderCard" style="width: *25rem; height: 430px;">
                <div class="media">
                    {% if item.photo %}
                    <img src="{{ item.photo.url }}"  height="250" width="*397" class="card-img-top">
                    {% endif %}
                </div>
                <div class="card-body">
                    <h5 class="card-title name">{{ item.name }}</h5>
                    <p class="card-text">{{ item.address }}</p>
                    <a href="{{ item.get_absolute_url }}" class="btn button">Читать</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

DogHome/MainPage/templates/MainPage/view_dog_list.html
{% extends 'base.html' %}

{%block title%}DogHome| {{ dog_item.name }}{%endblock%}


{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col md-5">
            <div class="media">
                {% if dog_item.photo %}
                <img class="custom-border" src="{{ dog_item.photo.url }}" width="600" height="600">
                {% else %}
                <img class="custom-border" src="https://images.freeimages.com/images/large-previews/349/free-background-blur-1636598.jpg" width="600" height="600">
                {% endif %}
            </div>
        </div>

        <div class="col-6 md-3">
            <div class="date">
                <h5 class="name">{{ dog_item.name }}</h5>
            </div>
            <div class="date">
                <p>Пол: {{ dog_item.get_gender_display }}</p>
            </div>
            <div class="date">
                <p>Вес: {{ dog_item.weight }}кг</p>
            </div>
            <div class="date">
                <p>Рост: {{ dog_item.height }}см</p>
            </div>
            <div class="date">
                <p>Описание: {{ dog_item.description }}</p>
            </div>
            <div class="date">
                <p>Был хозяин: {{ dog_item.get_owner_display}}</p>
            </div>
            <div class="date">
                <p>Возраст: {{ dog_item.age }}</p>
            </div>
            <div class="date">
                <p>Окрас: {{ dog_item.color }}</p>
            </div>
            <div class="date">
                <p>Порода: {{ dog_item.breed }}</p>
            </div>
            <div class="date">
                <p>Здоровье: {{ dog_item.health }}</p>
            </div>
            <div class="date">
                <a href="{% url 'viewshelter' dog_item.shelter.id %}">
                    Приют: {{ dog_item.shelter }}
                </a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

DogHome/MainPage/templates/MainPage/view_shelter_list.html
{% extends 'base.html' %}

{%block title%}DogHome | {{ shelters.name }}{%endblock%}


{% block content %}
<div class="container mt-4">
    <div class="row align-items-center">
        <div class="col-md-6">
            <div class="row text-center">
                <div class="col-md-12">
                    <div class="media">
                        <img src="{{ shelters.photo.url }}" width="600" height="300" class="img-fluid ml-3 custom-border">
                    </div>
                </div>

                {% for photo in shelter_photos %}
                <div class="col-md-4">
                    <img  style="width: 12em; height: 8em;" src="{{ photo.image.url }}" class="img-thumbnail">
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="col-md-6">
            <div class="col-12 md-3">
                <div class="date">
                    <h5 class="name">{{ shelters.name }}</h5>
                </div>
                <div class="date">
                    <p>Год создания: {{ shelters.year_of_creation|date:"Y"}}</p>
                </div>
                <div class="date">
                    <a href="{% url 'shelterbydogs' shelters.id %}">
                        Количество животных: {{ shelters.number_of_animals }}
                    </a>
                </div>
                <div class="date">
                    <p>Описание: {{ shelters.description }}</p>
                </div>
                <div class="date">
                    <p>Адрес: {{shelters.address}} д.</p>
                </div>
                <div class="date">
                    <p>Контакты: {{shelters.contacts}}</p>
                </div>
                <div class="date">
                    <a href="{% url 'helpforshelters'%}">
                        Контактное лицо: {{shelters.contact_person}}
                    </a>

                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}